language: nodejs
node_js:
  - 10

before_script:
  - npm install
  - npm run build

script:
  - npm run lint
  - npm run test

after_success:
  - npm pack

before_deploy:
  - export ZIP_FILE=$(ls | grep .tgz)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: $ZIP_FILE
    skip_cleanup: true
    on:
      branch: release
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: release
